sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed

collections:
  # sass_dir:
  #   output: true
  notes:
    output: true
  posts:
    output: true

feed:
  path: feed.xml
  custom_path: _includes/custom_feed.xml

description: "Kai Qu's home page on the World Wide Web"
