sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed

collections:
  notes:
    output: true
  posts:
    output: true
  stories:
    output: true

feed:
  path: feed.xml
  custom_path: _includes/custom_feed.xml

description: "Kai Qu's home page on the World Wide Web"
